---

- name: Create swap file
  command: dd if=/dev/zero of={{ swap.file_path }} bs=1024 count={{ swap.file_size_mb }}k
           creates="{{ swap.file_path }}"
  tags:
    - swap.file.create

- name: Change swap file permissions
  file: path="{{ swap.file_path }}"
        owner=root
        group=root
        mode=0600
  tags:
    - swap.file.permissions

- name: Check swap file type
  command: file {{ swap.file_path }}
  register: swapfile
  tags:
    - swap.file.mkswap

- name: Make swap file
  command: "sudo mkswap {{ swap.file_path }}"
  when: swapfile.stdout.find('swap file') == -1
  tags:
    - swap.file.mkswap

- name: Write swap entry in fstab
  mount: name=none
         src={{ swap.file_path }}
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
  tags:
    - swap.fstab

- name: Mount swap
  command: "swapon {{ swap.file_path }}"
  when: ansible_swaptotal_mb < 1
  tags:
    - swap.file.swapon

- name: configure swappiness
  lineinfile: dest=/etc/sysctl.conf line="vm.swappiness = {{ swap.swappiness }}" regexp="^vm.swappiness[\s]?=" state=present
  notify: sysctl
  when: swap.swappiness != false

- name: configure vm.vfs_cache_pressure
  lineinfile: dest=/etc/sysctl.conf line="vm.vfs_cache_pressure = {{ swap.vfs_cache_pressure }}" regexp="^vm.vfs_cache_pressure[\s]?=" state=present
  notify: sysctl
  when: swap.vfs_cache_pressure != false
